name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.1
  - seaborn=0.11.1
  - pandas=1.5.3
  - pip=23.0.1
  - pandas-profiling=3.5.0
  - pyarrow=11.0.0
  - pip:
      - wandb==0.13.10
      - ipywidgets==8.0.4