name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0.1
  - mlflow=2.0.1
  - pip:
      - wandb==0.13.10
      - lightgbm==3.3.4
      - scikit-learn==0.24.1
      - git+https://github.com/dangstan/build-ml-pipeline_main.git#egg=wandb-utils&subdirectory=components
