name: advanced_feature_engineer
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0.1
  - mlflow=2.0.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - scikit-learn==1.1.3
      - wandb==0.13.10
      - lightgbm==3.3.4