name: advanced_feature_engineer
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - mlflow==2.0.1
      - scikit-learn==1.2.1
      - wandb==0.13.10
      - lightgbm==3.3.4